name: "nightly"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      VDK: release
      VDK_FRONTEND: noninteractive
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up SSH"
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VDK_DEPLOY_KEY }}

      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: "Install VDK"
        run: |
          .ci/install_vdk.sh

      - name: "Run Tests"
        run: |
          .ci/test_script.sh
